@Bibliotheques_HostAddress = http://localhost:5121

### GET - Toutes les bibliothèques
GET {{Bibliotheques_HostAddress}}/bibliotheques
Accept: application/json

###

### GET - Bibliothèque par ID
GET {{Bibliotheques_HostAddress}}/bibliotheques/1
Accept: application/json

###

### POST - Ajouter une bibliothèque
POST {{Bibliotheques_HostAddress}}/bibliotheques
Content-Type: application/json

{
    "nom": "Bibliothèque de Limoilou",
    "adresse": "801, 3e Avenue",
    "capacite": 20000
}

###

### PUT - Modifier une bibliothèque
PUT {{Bibliotheques_HostAddress}}/bibliotheques/1
Content-Type: application/json

{
    "nom": "Bibliothèque des Étoiles",
    "adresse": "10, rue des Érables",
    "capacite": 150
}

###

### DELETE - Supprimer une bibliothèque
DELETE {{Bibliotheques_HostAddress}}/bibliotheques/2

###

### GET - Filtrer
GET {{Bibliotheques_HostAddress}}/bibliotheques/filtre?nom=
Accept: application/json

###